import json
import sys
import os
import shutil
import gdspy
import pandas as pd
import importlib.util
import glob
import os
import re
import argparse


from PRIMITIVE_GENERATORS import gen_inductor_layout as gen_ind
from PRIMITIVE_GENERATORS import gen_capacitor_layout as gen_cap
from PRIMITIVE_GENERATORS import gen_resistor_layout as gen_res
from PRIMITIVE_GENERATORS import gen_bbox_layout as gen_bbox
from PRIMITIVE_GENERATORS import gen_cpwd_layout as gen_cpwd
from PRIMITIVE_GENERATORS import gen_tline_layout as gen_tline
from PRIMITIVE_GENERATORS import gen_casmos_layout as gen_casmos
from PRIMITIVE_GENERATORS import read_pdk as read_pdk

from PRIMITIVE_OPTIMIZERS import optimize_capacitor as my_C_optimizer
from PRIMITIVE_OPTIMIZERS import optimize_inductor as my_L_optimizer
from PRIMITIVE_OPTIMIZERS import optimize_resistor as my_R_optimizer
from PRIMITIVE_OPTIMIZERS import optimize_tline as my_TL_optimizer
from PRIMITIVE_OPTIMIZERS import optimize_cpwd as my_CPWD_optimizer
from PRIMITIVE_OPTIMIZERS import emx_estimator as my_emx

from rf_logger import *

logger = get_rf_logger()


base = os.environ["PROJECT_HOME"]           # get the directory



def load_config(config_path):
    with open(config_path, "r") as f:
        cfg = json.load(f)
    return cfg

def get_net_weights(net_dict, ask_user=False, out_file=None):
    """
    Update the 'weight' field of each net in a nested dict.
    
    Args:
        net_dict : dict
            Dictionary of {net_name: {"weight": float, "endpoints": [...]}}
        ask_user : bool
            If True, will ask user to overwrite weights interactively
        out_file : str or None
            If provided, save the updated dict to this JSON file
    
    Returns:
        dict with updated weights
    """
    updated_dict = {}

    for net, details in net_dict.items():
        default_w = details.get("weight", 1.0)
        new_details = details.copy()
        
        if ask_user:
            try:
                val = input(f"Enter weight for {net} (default={default_w}): ").strip()
                new_details["weight"] = float(val) if val else float(default_w)
            except ValueError:
                print(f"Invalid input for {net}, keeping default {default_w}")
                new_details["weight"] = float(default_w)
        else:
            if NET_WEIGHTS_JSON == None:
                new_details["weight"] = float(1)
            else:
                if net in NET_WEIGHTS_JSON :
                    new_details["weight"] = float(NET_WEIGHTS_JSON[net])
                else:
                    new_details["weight"] = float(1) #Dummy nets generated by DECAPS which are not part of the input netlist
            

        updated_dict[net] = new_details

    # Optionally save to JSON
    if out_file:
        with open(out_file, "w") as f:
            json.dump(updated_dict, f, indent=4)
        print(f"Updated net weights saved to {out_file}")

    return updated_dict


def parse_weights(in_json="best_lna_multiobjective.json"):
    """
    Parse and pretty-print the contents of the best design JSON file.
    """
    net_weights= None
    branch_weights = None
    with open(in_json, "r") as f:
        data = json.load(f)
    if "nets" in data:
        net_weights = data["nets"]
    if "branches" in data:
        branch_weights = data["branches"]
    return net_weights, branch_weights
    
def parse_json(in_json="best_lna_multiobjective.json"):
    """
    Parse and pretty-print the contents of the best design JSON file.
    """
    with open(in_json, "r") as f:
        data = json.load(f)
    return data 


#Glabally accessible variables
NET_WEIGHTS_JSON = None
BRANCH_WEIGHT_JSON = None
emx_estimator_rf_model = None
knn_model = None
knn_geom_train = None
tline_df = None
poly_model = None
small_poly_model = None
layers = None
layernames = None 
labellayers = None
layerspecs = None




def parse_netlist(path, add_decaps=False, num_decaps=0, decap_val=500e-15,
                  vdd_net='net3', gnd_net='gnd'):
    with open(path) as f:
        lines = [l.strip() for l in f if l.strip() and not l.startswith('*')]

    subckts = {}
    current = None
    pattern = re.compile(r'^(.*?)\s*\((.*?)\)\s*$')
    for line in lines:
        line = line.strip()
        if not line:
            continue
        if line.lower().startswith('.subckt'):
            parts = line.split()
            name = parts[1]
            current = {"name": name, "instances": []}
            subckts[name] = current

        elif line.lower().startswith('.ends'):
            current = None

        elif current is not None:

            m = pattern.match(line)
            if m:
                non_bracket = m.group(1).strip()
                bracket = m.group(2).strip()
            else:
                non_bracket = line
                bracket = None
            
            parts = non_bracket.split()
            if bracket != None:
                parts_attr = bracket.split()
            inst_name = parts[0]
            
            cell = parts[-1]

            if cell.upper() in ['RES', 'CAP', 'IND', 'CASMOS', 'CPWD']:  #All instances of some attribute should be in this list
                try:
                    inst_attr = float(parts[-2])
                except ValueError:
                    inst_attr = None
                nets = parts[1:-2]
                if cell.upper() in ['RES', 'CAP'] and bracket!=None: #Expects only Resistor or Capacitor value
                    inst_attr = float(parts_attr[0])
                elif cell.upper() == 'IND' and bracket!=None:
                    ind_l = float(parts_attr[0])
                    ind_q = None if parts_attr[1] == "-1" else float(parts_attr[1])
                    ind_qf = None if parts_attr[2] == "-1" else float(parts_attr[2])
                    ind_srf = None if parts_attr[3] == "-1" else float(parts_attr[3])
                    inst_attr = (ind_l, ind_q, ind_qf, ind_srf)
                    nets = parts[1:4]
                    if ind_l is not None and ind_l < 100:  # (pH)
                        cell = 'TLINE'
                        nets = parts[1:4]
                elif cell.upper() == 'IND' and bracket==None:
                    ind_l = float(parts[-2])
                    ind_q = None 
                    ind_qf = None 
                    ind_srf = None 
                    inst_attr = (ind_l, ind_q, ind_qf, ind_srf)
                    nets = parts[1:4]
                    if ind_l is not None and ind_l < 100:  # (pH)
                        cell = 'TLINE'
                        nets = parts[1:4]
                        
                elif cell.upper() == 'CPWD':
                    l = float(parts_attr[0])
                    w = float(parts_attr[1])
                    s = float(parts_attr[2])
                    inst_attr = (l, w, s)
                    nets = parts[1:5]

                elif cell.upper() == 'CASMOS':
                    l = float(parts_attr[0])
                    fw = float(parts_attr[1])
                    nf = float(parts_attr[2])
                    inst_attr = (l, fw, nf)
                    nets = parts[1:6]
            else:           #ALl the blackboxes should be in ELSE
                inst_attr = None
                nets = parts[1:-1]

            current["instances"].append({
                "inst_name": inst_name,
                "cell": cell,
                "nets": nets,
                "inst_attr": inst_attr
            })

        # -------------------------------------------------------
        # ADD EXTRA INSTANCES AFTER PARSING (to ALL subckts)
        # -------------------------------------------------------
        if add_decaps and subckts:
            print(f"Adding {num_decaps} decaps each of {decap_val} F")
            for subckt in subckts.values():
                for i in range(num_decaps):
                    subckt["instances"].append({
                        "inst_name": f"auto_gen_decap_{subckt['name']}_{i}",
                        "cell": 'CAP',
                        "nets": [vdd_net, gnd_net],
                        "val": decap_val,
                        "emx": (None, None)
                    })
    return subckts

def build_nets(subckts, top_name, net_weights=None):
    """
    Build net connectivity from subcircuits.

    Args:
        subckts (dict): Parsed subcircuits
        top_name (str): Name of top subckt
        net_weights (dict, optional): Mapping {net_name: weight}, defaults to 1.0 if not provided

    Returns:
        dict: {
          net_name: {
            "weight": float,
            "endpoints": [
              {"module": str, "pin": str or None, "pin_index": int or None}, ...
            ]
          }, ...
        }
    """
    if net_weights is None:
        net_weights = {}

    top = subckts[top_name]
    nets = {}

    for inst in top["instances"]:
        nets_field = inst["nets"]

        # Case 1: nets is a dict {pin: net}
        if isinstance(nets_field, dict):
            for pin, net in nets_field.items():
                if "pins" in inst and pin in inst["pins"]:
                    pin_index = inst["pins"].index(pin)
                else:
                    pin_index = None
                nets.setdefault(net, {
                    "weight": net_weights.get(net, 1.0),
                    "endpoints": []
                })
                nets[net]["endpoints"].append({
                    "module": inst["inst_name"],
                    "pin": pin,
                    "pin_index": pin_index
                })

        # Case 2: nets is a list of net names
        elif isinstance(nets_field, list):
            for i, net in enumerate(nets_field):
                nets.setdefault(net, {
                    "weight": net_weights.get(net, 1.0),
                    "endpoints": []
                })
                nets[net]["endpoints"].append({
                    "module": inst["inst_name"],
                    "pin_index": i,
                    "pin_name" : net
                })

        # Case 3: nets is a single net string
        elif isinstance(nets_field, str):
            net = nets_field
            nets.setdefault(net, {
                "weight": net_weights.get(net, 1.0),
                "endpoints": []
            })
            nets[net]["endpoints"].append({
                "module": inst["inst_name"],
                "pin_index": 0,
                "pin_name": net
            })

        else:
            raise TypeError(f"Unexpected nets format: {nets_field}")

    return nets



def extract_cell_geometry(
    gds_file,
    pin_layers= None,
    pin_order=None,
    nets=None,
    scale=1000,
):
    """
    Extract cell bounding box and pin locations (with names, bbox, and label center) from a GDS file.
    The geometry is first translated so that the cell's overall bbox lower-left sits at (0,0).

    Returns:
        (bbox, w, h, pins):
            bbox (tuple): (0, 0, w, h) box of the translated cell
            w (float): width of cell
            h (float): height of cell
            pins (list of dict): 
                [
                  {
                    "name": str or None,
                    "layer": int,
                    "datatype": int,
                    "bbox": [px0, py0, px1, py1],   # ints (scaled)
                    "x": int,  # pin bbox center (scaled)
                    "y": int,
                    "lx": int or None,  # nearest label anchor (scaled) if any
                    "ly": int or None,
                    "net_name": str or None
                  },
                  ...
                ]
    """
    lib = gdspy.GdsLibrary(infile=gds_file)
    topcells = lib.top_level()
    if not topcells:
        raise ValueError(f"No top cell found in {gds_file}")
    topcell = topcells[0]

    # --- compute full-cell bbox from all polygons (absolute coords from gdspy) ---
    spec_map_full = topcell.get_polygons(by_spec=True)
    all_polys = []
    for polys in spec_map_full.values():
        all_polys.extend(polys)
    if not all_polys:
        raise ValueError(f"No polygons found in {gds_file}")

    all_points = [pt for poly in all_polys for pt in poly]
    x_coords, y_coords = zip(*all_points)
    raw_x0, raw_y0, raw_x1, raw_y1 = min(x_coords), min(y_coords), max(x_coords), max(y_coords)
    w = float(raw_x1 - raw_x0)
    h = float(raw_y1 - raw_y0)

    # Offset to translate LL to (0,0) without mutating the GDS
    dx, dy = -raw_x0, -raw_y0

    # --- collect text labels (for pin names) and translate them by (dx, dy) ---
    raw_texts = [(lbl.text, float(lbl.position[0]), float(lbl.position[1])) for lbl in topcell.get_labels()]
    texts = [(txt, tx + dx, ty + dy) for (txt, tx, ty) in raw_texts]

    # --- pin extraction on requested (layer, datatype) pairs, translating by (dx, dy) ---
    pins = []
    for layer in pin_layers:
        for poly in spec_map_full.get(layer, []):
            # bbox of pin polygon, then translate
            px0, py0 = poly.min(axis=0)
            px1, py1 = poly.max(axis=0)
            px0_t, py0_t = float(px0 + dx), float(py0 + dy)
            px1_t, py1_t = float(px1 + dx), float(py1 + dy)
            cx_t,  cy_t  = (px0_t + px1_t) / 2.0, (py0_t + py1_t) / 2.0

            # find nearest label for pin name (after translation)
            name, lx_t, ly_t = None, None, None
            if texts:
                # Manhattan distance is fine here
                dists = [(abs(cx_t - tx) + abs(cy_t - ty), txt, tx, ty) for (txt, tx, ty) in texts]
                _, name, lx_t, ly_t = min(dists, key=lambda x: x[0])

            pins.append({
                "name": name,
                "layer": layer[0],
                "datatype": layer[1],
                "bbox": [int(px0_t * scale), int(py0_t * scale), int(px1_t * scale), int(py1_t * scale)],
                "x":   int(cx_t * scale),
                "y":   int(cy_t * scale),
                "lx":  int(lx_t * scale) if lx_t is not None else None,
                "ly":  int(ly_t * scale) if ly_t is not None else None,
                "net_name": None,
                "width": max(abs(int(py1_t * scale) -  int(py0_t * scale)), abs(int(px1_t * scale) - int(px0_t * scale)))
            })

    # --- reorder pins if pin_order is given, and attach net names if provided ---
    if pin_order:
        if nets and len(nets) != len(pin_order):
            raise ValueError("nets must have same length as pin_order")

        name_to_pins = {}
        for p in pins:
            if p["name"] is not None:
                name_to_pins.setdefault(p["name"], []).append(p)

        ordered = []
        for i, n in enumerate(pin_order):
            if n in name_to_pins:
                for p in name_to_pins[n]:
                    if nets:
                        p["net_name"] = nets[i]
                    ordered.append(p)

        remaining = [p for p in pins if p["name"] not in (pin_order or [])]
        pins = ordered + remaining

    # After translation, bbox LL is (0,0), UR is (w, h)
    return (int(0), int(0), int(w * scale), int(h * scale)), int(w * scale), int(h * scale), pins


def parse_gds_directory(gds_dir, subckts, top_name, pad_dir, pad_mode="periphery", net_weights=None, branch_weights = BRANCH_WEIGHT_JSON, scale = 1000):
    """
    Generate GDS variants for each instance and build both modules and nets simultaneously.
    """
    modules = {}
    nets = {}

    top = subckts[top_name]

    if net_weights is None:
        net_weights = {}
    logger.info(f"Storing all the primitives in the directory {gds_dir}")
    def update_nets(inst_name, pin_order, pins, inst_nets):
        """
        Attach net names to pins and update the global nets dict.
        Also generates branches for each net (star model) with deduplication.
        """
        for i, p in enumerate(pins):
            if i < len(inst_nets):
                net_name = inst_nets[i]
                p["net_name"] = net_name

                # Initialize net entry if not exists
                nets.setdefault(net_name, {
                    "weight": net_weights.get(net_name, 1.0),
                    "endpoints": [],
                    "branches": []
                })

                # Check if endpoint already exists
                existing_eps = nets[net_name]["endpoints"]
                found = False
                for ep in existing_eps:
                    if ep["module"] == inst_name and ep["pin_index"] == i:
                        if p["width"] > ep["width"]:
                            ep["width"] = p["width"]
                        found = True
                        break

                # Add new endpoint
                if not found:
                    nets[net_name]["endpoints"].append({
                        "module": inst_name,
                        "pin_name": pin_order[i] if i < len(pin_order) else None,
                        "pin_index": i,
                        "width": p["width"]
                    })

            eps = nets[net_name]["endpoints"]

            if len(eps) <= 1:
                nets[net_name]["branches"] = []
            else:
                # Convert endpoints to "module/pin_name"
                ep_names = []
                for ep in eps:
                    m = ep["module"]
                    pnm = ep.get("pin_name")
                    if pnm is None:
                        pnm = f"p{ep['pin_index']}"
                    ep_names.append(f"{m}/{pnm}")

                anchor = ep_names[0]

                branch_set = set()

                for other in ep_names[1:]:
                    branch_set.add((anchor, other))

                branch_list = []

                for (a, b) in branch_set:

                    # -----------------------------
                    # Handle branch_weights = None
                    # -----------------------------
                    if branch_weights is None:
                        w = 0
                    else:
                        key1 = f"{a}__{b}"
                        key2 = f"{b}__{a}"

                        if key1 in branch_weights:
                            w = branch_weights[key1]
                        elif key2 in branch_weights:
                            w = branch_weights[key2]
                        else:
                            w = 0

                    branch_list.append((a, b, w))

                nets[net_name]["branches"] = branch_list


    peri_pad_w = None
    peri_pad_h = None

    for inst in top["instances"]:
        inst_name = inst["inst_name"]
        cell = inst["cell"]
        inst_nets = inst["nets"]
        val = inst["inst_attr"]
        bar = "=" * 200
        logger.info(f"{bar}")
        logger.info(f"Creating layout for {inst_name} -> {cell} with nets {inst_nets}")
        variants = []
        pad_only, pad_sides = False, None

        # ------------------ INDUCTORS ------------------
        if cell == 'IND':
            pad_only = False
            pin_order = ['P1', 'P2', 'GND']
            target = val
            optimization_results = my_L_optimizer.optimize_specs_multi_variant(
                target_specs=target,
                emx_estimator_model=emx_estimator_rf_model,
                knn_model=knn_model,
                knn_train_data=knn_geom_train,
                four_variants=True
            )
            
            for var, result in optimization_results['variants'].items():
                if result['mode'] != 'no_match':
                    logger.info(f"\nGenerating layout for variant {var} with predicted specs {result['pred_spec']}")
                    gds_file_path = os.path.join(gds_dir, f"{inst_name}_{var}.gds")
                    gen_ind.generate_standard_inductor(
                        num_turns=result['geometry'][3],
                        inner_radius=result['geometry'][0],
                        clearance=result['geometry'][2],
                        num_sides=8,
                        width=result['geometry'][1],
                        shield_space_from_p2=20,
                        port_extension_length=20,
                        shield_metal_width=10,
                        layers=layers, layernames=layernames,
                        labellayers=labellayers, layerspecs=layerspecs,
                        pgs=False,
                        gds_name=f"{inst_name}_{var}",
                        output_dir=gds_dir, follow_coil_shape = True
                    )
                    (x0, y0, x1, y1), w, h, pins = extract_cell_geometry(
                        gds_file_path, pin_order=pin_order, scale = scale, pin_layers= list(labellayers.values())
                    )
                    logger.info(f"Layout generated with ll = {(x0, y0)} and ur = {(x1, y1)}, width  = {w} and height = {h} and pins = {pins}")
                    update_nets(inst_name, pin_order, pins, inst_nets)
                    variants.append({
                        "ll": [x0, y0], "ur": [x1, y1],
                        "w": w, "h": h,
                        "pins": pins,
                        "gds_file": gds_file_path
                    })
            
        # ------------------ TLINE ------------------
        elif cell == 'TLINE':
            pad_only = False
            pin_order = ['P1', 'P2']
            logger.info(f"Generating 1 variant for the {cell} {inst_name}")
            
            tline_l, tline_w, tline_ind = my_TL_optimizer.optimize_tline(df=tline_df, input_col="Inductance", target_cols=["Length","Width"], n_neighbors=3, query_point = val[0])
            logger.info(f"Generating layout with predicted specs {tline_ind}")
            gds_file_path = os.path.join(gds_dir, f"{inst_name}.gds")
            gen_tline.create_tline(
                length = tline_l,
                width = tline_w,
                gds_name = f"{inst_name}",
                gds_dir = gds_dir,
                layer_datatypes=layers, layer_num=layernames,
                label_layers=labellayers, layer_rules=layerspecs
            )
            (x0, y0, x1, y1), w, h, pins = extract_cell_geometry(
                gds_file_path, pin_order=pin_order, scale = scale, pin_layers= list(labellayers.values())
            )
            logger.info(f"Layout generated with ll = {(x0, y0)} and ur = {(x1, y1)}, width  = {w} and height = {h} and pins = {pins}")
            update_nets(inst_name, pin_order, pins, inst_nets)
            variants.append({
                "ll": [x0, y0], "ur": [x1, y1],
                "w": w, "h": h,
                "pins": pins,
                "gds_file": gds_file_path
            })
        # ------------------ CAPACITORS ------------------
        elif cell == 'CAP':
            pad_only = False
            pin_order = ['PLUS', 'MINUS', 'BULK1', 'BULK2']
            logger.info(f"Generating 1 variant for the {cell} {inst_name}")
            logger.info(f"Required specs : {val/1e-15}")

            if val /1e-15 > 50:
                _, cap_results = my_C_optimizer.find_candidates_fast(
                    C_target=val/1e-15, poly_model=poly_model,
                    aspect_ratios=[1, 2, 3], W_min=4, W_max=100, tol_frac=0.1
                )
                for aspect_ratio, (l, w_, pred_cap) in cap_results.items():
                    logger.info(f"\n Generating layout for the variant with aspect ratio {aspect_ratio} with dimensions {l,w} and estimated cap {pred_cap}")
                    gds_file_path = os.path.join(gds_dir, f"{inst_name}_{aspect_ratio}.gds")
                    gen_cap.create_interdigitated_capacitor(
                        cap_length=l, cap_width=w_,
                        layer_datatypes=layers, layer_num=layernames,
                        label_layers=labellayers, layer_rules=layerspecs,
                        output_dir=gds_dir, output_gds=f"{inst_name}_{aspect_ratio}"
                    )
                    (x0, y0, x1, y1), w, h, pins = extract_cell_geometry(
                        gds_file_path, pin_order=pin_order, scale = scale, pin_layers= list(labellayers.values())
                    )
                    logger.info(f"Layout generated with ll = {(x0, y0)} and ur = {(x1, y1)}, width  = {w} and height = {h} and pins = {pins}")
                    update_nets(inst_name, pin_order, pins, inst_nets)
                    variants.append({
                        "ll": [x0, y0], "ur": [x1, y1],
                        "w": w, "h": h,
                        "pins": pins,
                        "gds_file": gds_file_path
                    })
            else:
                _, cap_results = my_C_optimizer.find_candidates_fast(
                    C_target=val/1e-15, poly_model=small_poly_model,
                    aspect_ratios=[1, 2, 3], W_min=4, W_max=100, tol_frac=0.1
                )
                pin_order = pin_order[:2]
                for aspect_ratio, (l, w_, pred_cap) in cap_results.items():
                    logger.info(f"\n Generating layout for the variant with aspect ratio {aspect_ratio} with dimensions {l,w} and estimated cap {pred_cap}")
                    gds_file_path = os.path.join(gds_dir, f"{inst_name}_{aspect_ratio}.gds")
                    gen_cap.create_small_mim_capacitor(
                        cap_length=l, cap_width=w_,
                        layer_datatypes=layers, layer_num=layernames,
                        label_layers=labellayers, layer_rules=layerspecs,
                        output_dir=gds_dir, output_gds=f"{inst_name}_{aspect_ratio}"
                    )
                    (x0, y0, x1, y1), w, h, pins = extract_cell_geometry(
                        gds_file_path, pin_order=pin_order, scale = scale, pin_layers= list(labellayers.values())
                    )
                    logger.info(f"Layout generated with ll = {(x0, y0)} and ur = {(x1, y1)}, width  = {w} and height = {h} and pins = {pins}")
                    update_nets(inst_name, pin_order, pins, inst_nets)
                    variants.append({
                        "ll": [x0, y0], "ur": [x1, y1],
                        "w": w, "h": h,
                        "pins": pins,
                        "gds_file": gds_file_path
                    })

        # ------------------ RESISTORS ------------------
        elif cell == 'RES':
            pad_only = False
            pin_order = ['PLUS', 'MINUS']
            logger.info(f"Generating 1 variant for the {cell} {inst_name}")
            logger.info(f"Required specs : {val}")
            res_results = my_R_optimizer.suggest_resistor_dims(R_target=val, k=3)
            print(res_results)
            for i, (l, w_, r_pred) in enumerate(res_results):
                logger.info(f"\nGenerating the layout for variant {i} with dimensios {l,w_} and estimated resistance {r_pred}")
                gds_file_path = os.path.join(gds_dir, f"{inst_name}_{i}.gds")
                gen_res.create_poly_res(
                    length=l, width=w_,
                    gds_name=f"{inst_name}_{i}",
                    gds_dir=gds_dir,
                    layer_datatypes=layers, layer_num=layernames,
                    label_layers=labellayers, layer_rules=layerspecs
                )
                (x0, y0, x1, y1), w, h, pins = extract_cell_geometry(
                    gds_file_path, pin_order=pin_order, scale = scale, pin_layers= list(labellayers.values())
                )
                logger.info(f"Layout generated with ll = {(x0, y0)} and ur = {(x1, y1)}, width  = {w} and height = {h} and pins = {pins}")
                update_nets(inst_name, pin_order, pins, inst_nets)
                variants.append({
                    "ll": [x0, y0], "ur": [x1, y1],
                    "w": w, "h": h,
                    "pins": pins,
                    "gds_file": gds_file_path
                })
        # ------------------ CPWD ------------------
        elif cell == 'CPWD':
            pad_only = False
            pin_order = ['P1', 'P2', 'GND1', 'GND2']
            cpwd_dim = (val[0], val[1], val[2])
            logger.info(f"\nGenerating 1 variant for the {cell} with dimensions {cpwd_dim}")
            gds_file_path = os.path.join(gds_dir, f"{inst_name}.gds")
            gen_cpwd.create_cpwd(
                length=cpwd_dim[0], width=cpwd_dim[1], gap = cpwd_dim[2],
                gds_name=f"{inst_name}",
                gds_dir=gds_dir,
                layer_datatypes=layers, layer_num=layernames,
                label_layers=labellayers, layer_rules=layerspecs
            )
            (x0, y0, x1, y1), w, h, pins = extract_cell_geometry(
                gds_file_path, pin_order=pin_order, scale = scale, pin_layers= list(labellayers.values())
            )
            logger.info(f"Layout generated with ll = {(x0, y0)} and ur = {(x1, y1)}, width  = {w} and height = {h} and pins = {pins}")
            update_nets(inst_name, pin_order, pins, inst_nets)
            variants.append({
                "ll": [x0, y0], "ur": [x1, y1],
                "w": w, "h": h,
                "pins": pins,
                "gds_file": gds_file_path
            })
        # ------------------ PAD ------------------
        elif cell == 'PAD':
            pad_only = True
            pad_sides = pad_dir
            logger.info(f"\nGenerating the variant for {cell}")
            gds_file_path = os.path.join(gds_dir, f"{inst_name}.gds")
            pin_order = ['PAD']
            if pad_mode == "periphery":
                pad_path = "FIXED_PRIMITIVES/pad.gds"
            else:
                pad_path = "FIXED_PRIMITIVES/bga.gds"
            gen_bbox.generate_bbox(
                input_gds=pad_path,
                output_gds=gds_file_path,
                new_name=inst_name
            )
            (x0, y0, x1, y1), w, h, pins = extract_cell_geometry(gds_file_path, pin_order=pin_order, scale = scale, pin_layers= list(labellayers.values()))
            peri_pad_w = w
            peri_pad_h = h
            logger.info(f"Layout generated with ll = {(x0, y0)} and ur = {(x1, y1)}, width  = {w} and height = {h} and pins = {pins}")
            update_nets(inst_name, pin_order, pins, inst_nets)
            variants.append({
                "ll": [x0, y0], "ur": [x1, y1],
                "w": w, "h": h,
                "pins": pins,
                "gds_file": gds_file_path
            })

        # ------------------ MOS TYPES ------------------
        elif cell in ['BIASMOS']: 
            pad_only = False
            logger.info(f"Generating variant for {cell}")
            pin_order = ['D', 'G', 'BS'] 
            in_gds = "FIXED_PRIMITIVES/nmos_bias_1.gds"
            gds_file_path = os.path.join(gds_dir, f"{inst_name}.gds")
            gen_bbox.generate_bbox(input_gds=in_gds, output_gds=gds_file_path, new_name=inst_name)
            (x0, y0, x1, y1), w, h, pins = extract_cell_geometry(gds_file_path, pin_order=pin_order, scale = scale, pin_layers= list(labellayers.values()))
            logger.info(f"Layout generated with ll = {(x0, y0)} and ur = {(x1, y1)}, width  = {w} and height = {h} and pins = {pins}")
            update_nets(inst_name, pin_order, pins, inst_nets)
            variants.append({
                "ll": [x0, y0], "ur": [x1, y1],
                "w": w, "h": h,
                "pins": pins,
                "gds_file": gds_file_path
            })
         # ------------------ MOS TYPES ------------------
        elif cell in ['LNA_DIFF', 'GC_MX']: 
            pad_only = False
            logger.info(f"Generating variant for {cell}")
            if cell == 'LNA_DIFF':
                pin_order = ['GP', 'GM', 'G1', 'G2', 'DP', 'DM', 'SP', 'SM'] 
                in_gds = "FIXED_PRIMITIVES/diff_lna.gds"
            elif cell == 'GC_MX':
                pin_order = ['R1', 'R2', 'L1', 'L2','GND', 'I1', 'I2', 'I11', 'I22'] #GND stays default
                in_gds = "FIXED_PRIMITIVES/gilbert_16x16.gds"
            gds_file_path = os.path.join(gds_dir, f"{inst_name}.gds")
            gen_bbox.generate_bbox(input_gds=in_gds, output_gds=gds_file_path, new_name=inst_name)
            (x0, y0, x1, y1), w, h, pins = extract_cell_geometry(gds_file_path, pin_order=pin_order, scale = scale, pin_layers= list(labellayers.values()))
            logger.info(f"Layout generated with ll = {(x0, y0)} and ur = {(x1, y1)}, width  = {w} and height = {h} and pins = {pins}")
            update_nets(inst_name, pin_order, pins, inst_nets)
            variants.append({
                "ll": [x0, y0], "ur": [x1, y1],
                "w": w, "h": h,
                "pins": pins,
                "gds_file": gds_file_path
            })
        # ------------------ MOS TYPES ------------------
        elif cell == 'CASMOS':
            pad_only = False
            pin_order = ['DD', 'G2', 'GG', 'SS', 'GND'] #GND stays default

            gds_file_path = os.path.join(gds_dir, f"{inst_name}.gds")
            nums = (val[0], val[1], val[2])
            gen_casmos.generate_casmos(
                length=int(nums[-1])/scale,
                fw=int(nums[1]),
                nf=int(nums[0])-2,
                layer_datatypes = layers, 
                layer_num = layernames, 
                label_layers = labellayers, 
                layer_rules = layerspecs,
                output_dir = gds_dir,
                output_gds = inst_name            
            )

            (x0, y0, x1, y1), w, h, pins = extract_cell_geometry(gds_file_path, pin_order=pin_order, scale = scale, pin_layers= list(labellayers.values()))
            logger.info(f"Layout generated with ll = {(x0, y0)} and ur = {(x1, y1)}, width  = {w} and height = {h} and pins = {pins}")
            update_nets(inst_name, pin_order, pins, inst_nets)
            variants.append({
                "ll": [x0, y0], "ur": [x1, y1],
                "w": w, "h": h,
                "pins": pins,
                "gds_file": gds_file_path
            })
        # ------------------ Finalize ------------------
        modules[inst_name] = {
            "variants": variants,
            "pad_only": pad_only,
            "pad_sides": pad_sides,
            "concrete_name": cell
        }
        
    return modules, nets, peri_pad_w, peri_pad_h

if __name__ == "__main__":


    parser = argparse.ArgumentParser(
        description="Parse a SPICE netlist, generate primitive layouts, and write design/nets JSON files."
    )
    parser.add_argument("--config", default="config.json", help="Input config.json with all user inputs")
    args = parser.parse_args()
    cfg = load_config(args.config)


    netlist_file = cfg["design"]["input_netlist"]    #sys.argv[1] if len(sys.argv) > 1 else "lna.sp"
    top_name = cfg['topcell']          #sys.argv[2] if len(sys.argv) > 2 else "lna"
    project_dir=cfg["project_name"]
    os.makedirs(project_dir, exist_ok=True)

    stage_2_dir = os.path.join(project_dir, "stage_2")
    os.makedirs(stage_2_dir, exist_ok=True)

    
    gds_dir = os.path.join(stage_2_dir, "primitives")
    os.makedirs(gds_dir, exist_ok=True)
    scale = cfg["scale"]


    #Net weights parsing
    net_weights_file = cfg["design"]["net_weights"]
    NET_WEIGHTS_JSON, BRANCH_WEIGHT_JSON = parse_weights(net_weights_file)
    log_section(logger, f"Reading the Nets weights from {net_weights_file}")
    if NET_WEIGHTS_JSON != None:
        for k, v in NET_WEIGHTS_JSON.items():
            logger.info(f"    {k:<35} : {v}")

    if BRANCH_WEIGHT_JSON != None:
        for k, v in BRANCH_WEIGHT_JSON.items():
            logger.info(f"    {k:<35} : {v}")


    ############PRELOADING INDUCTOR DEPENDENCIES################
    dataset_path = cfg["datasets"]["spiral_inductor"]
    log_section(logger, "Setting up the KNN and EMX surrogate models")
    emx_estimator_rf_model, knn_model, knn_geom_train = my_L_optimizer.setup_all_models(dataset_path)

    
    ##############PRELOADING TLINE DATASET#############################
    tline_dataset = cfg["datasets"]["tline"]
    log_section(logger, f"Preloading T-Line dataset from {tline_dataset} for Tline estimation")
    tline_df = pd.read_csv(tline_dataset)

    ################PRELOADING CAPACITOR DEPENDENCIES##################
    mimcap_dataset = cfg["datasets"]["mimcap"]
    small_mimcap_dataset = cfg["datasets"]["small_mimcap"]
    log_section(logger, f"Setting up the MIM CAP poly model using dataset {mimcap_dataset}")
    poly_model = my_C_optimizer.train_poly_model(mimcap_dataset, degree=2, model_path = os.path.join(base, "DEV", "MODELS", "mimcap_poly_model.pkl"))
    small_poly_model = my_C_optimizer.train_poly_model(small_mimcap_dataset, degree=2, model_path = os.path.join(base, "DEV", "MODELS", "small_mimcap_poly_model.pkl"))

    #Parsing netlist
    subckts = parse_netlist(netlist_file, num_decaps = cfg['decaps']['num_decaps'], add_decaps = cfg['decaps']['add_decaps'], decap_val = cfg['decaps']['decap_val']) 
    for k, v in subckts.items():
        logger.info(f"Subckt {k}")
        logger.info(f"Name: {v['name']}")
        for instance in v['instances']:
            logger.info(f"Instance name : {instance['inst_name']}")
            logger.info(f"Cell : {instance['cell']}")
            logger.info(f"Nets : {instance['nets']}")
            logger.info(f"Attributre : {instance['inst_attr']}")

    
    pad_dir =cfg["pad_direction"]
    logger.info(f"Using directions {pad_dir} for the I/O PADS")
   
    pdk_file = cfg["pdk"]
    logger.info(f"Parsing the pdk file from {pdk_file}")
    layers, layernames,labellayers, layerspecs, design_info = read_pdk.readLayerInfo(pdk_file, scale=scale)

    log_section(logger, "Primitive layout generation")
    modules, nets, peri_pad_w, peri_pad_h = parse_gds_directory(gds_dir = gds_dir, subckts=subckts, top_name=top_name, pad_dir = pad_dir, pad_mode=cfg['pad_mode'], scale = scale)

    nets = get_net_weights(nets, ask_user = False)
    # remove duplicate endpoints in-place
    for net_data in nets.values():
        seen = set()
        unique_endpoints = []
        for ep in net_data["endpoints"]:
            key = (ep["module"], ep.get("pin_name"), ep.get("pin_index"))
            if key not in seen:
                seen.add(key)
                unique_endpoints.append(ep)
        net_data["endpoints"] = unique_endpoints
    if cfg['pad_mode']=="periphery":
        design = {
            "chip": {
                "pitch": 0,
                "io_pitch": int(design_info['periphery_pad_pitch']),
                "io_w": int(peri_pad_w),
                "io_h": int(peri_pad_h)
            },
            "modules": modules,
            "nets": nets
        }
    elif cfg['pad_mode']=="bga":
        design = {
            "chip": {
              "pad_mode": "bga",
              "bga_pitch_x": design_info['bga_pitch_x'],
              "bga_pitch_y": design_info['bga_pitch_y'],
              "bga_origin_x": 0,
              "bga_origin_y": 0
              },
            "modules": modules,
            "nets": nets
        }
    
    output_design = os.path.join(stage_2_dir, f'{top_name}_design.json')
    with open(output_design, "w") as f:
        json.dump(design, f, indent=2)

    # Save a separate JSON with only nets
    output_design_nets = os.path.join(stage_2_dir, f'{top_name}_nets.json')
    nets_only = {"nets": nets}
    with open(output_design_nets, "w") as f:
        json.dump(nets_only, f, indent=2)

    print(f"Final design and nets exported to {output_design} and {output_design_nets} respectively.")
